CREATE TABLE IF NOT EXISTS category (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    color VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS todo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
    detail VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    category_id BIGINT NOT NULL DEFAULT 1,
    deadline DATE,
    CONSTRAINT fk_todo_category FOREIGN KEY (category_id) REFERENCES category(id)
);
